name: Making Pact
author: Various Makers of Pact
baseurl: 
description: Problems | Process | Product
github: http://www.github.com/pactcoffee
twitter: http://www.twitter.com/pactcoffee
facebook: http://www.facebook.com/pactcoffee
email: dev@pactcoffee.com
location: UK
disqus: pactcoffee

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
